// Copyright Epic Games, Inc. All Rights Reserved.

#include "Muniz_GAM415Projectile.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "Components/SphereComponent.h"
#include "Kismet/KismetMathLibrary.h"
#include "components/DecalComponent.h"
#include "kismet/GameplayStatics.h"
#include "NiagaraFunctionLibrary.h"
#include "NiagaraComponent.h"




AMuniz_GAM415Projectile::AMuniz_GAM415Projectile() 
{
	// Use a sphere as a simple collision representation
	CollisionComp = CreateDefaultSubobject<USphereComponent>(TEXT("SphereComp"));
	CollisionComp->InitSphereRadius(5.0f);
	CollisionComp->BodyInstance.SetCollisionProfileName("Projectile");
	CollisionComp->OnComponentHit.AddDynamic(this, &AMuniz_GAM415Projectile::OnHit);		// set up a notification for when this component hits something blocking

	// Players can't walk on it
	CollisionComp->SetWalkableSlopeOverride(FWalkableSlopeOverride(WalkableSlope_Unwalkable, 0.f));
	CollisionComp->CanCharacterStepUpOn = ECB_No;

	ProjectileMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Projectile Mesh"));
	

	// Set as root component
	RootComponent = CollisionComp;
	ProjectileMesh->SetupAttachment(CollisionComp);

	// Use a ProjectileMovementComponent to govern this projectile's movement
	ProjectileMovement = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileComp"));
	ProjectileMovement->UpdatedComponent = CollisionComp;
	ProjectileMovement->InitialSpeed = 3000.f;
	ProjectileMovement->MaxSpeed = 3000.f;
	ProjectileMovement->bRotationFollowsVelocity = true;
	ProjectileMovement->bShouldBounce = true;

	// Die after 3 seconds by default
	InitialLifeSpan = 3.0f;
}

//Sets the projectile material to a dynamic instance material. Color is randomized with randColor.
void AMuniz_GAM415Projectile::BeginPlay()
{
	Super::BeginPlay();
	randColor = FLinearColor(UKismetMathLibrary::RandomFloatInRange(0.f, 1.f), UKismetMathLibrary::RandomFloatInRange(0.f, 1.f), UKismetMathLibrary::RandomFloatInRange(0.f, 1.f), 1.f);

	dmiMat = UMaterialInstanceDynamic::Create(projectileMaterial, this);
	ProjectileMesh->SetMaterial(0, dmiMat);

	dmiMat->SetVectorParameterValue("ProjectileColor", randColor);
}

void AMuniz_GAM415Projectile::OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit)
{
	// Only add impulse and destroy projectile if we hit a physics actor
	if ((OtherActor != nullptr) && (OtherActor != this) && (OtherComp != nullptr) && OtherComp->IsSimulatingPhysics())
	{
		OtherComp->AddImpulseAtLocation(GetVelocity() * 100.0f, GetActorLocation());

		Destroy();
	}

	//If collision is valid... Spawn decal at hit location. Splat pattern will depend on number generated by frameNum
	if (OtherActor != nullptr)
	{
	    
		
		float frameNum = UKismetMathLibrary::RandomFloatInRange(0.f, 3.f);

		//creates decal and spawns at hit location
		auto Decal = UGameplayStatics::SpawnDecalAtLocation(GetWorld(), baseMaterial, FVector(UKismetMathLibrary::RandomFloatInRange(20.f, 40.f)), Hit.Location, Hit.Normal.Rotation(), 0.f);
		auto matInstance = Decal->CreateDynamicMaterialInstance();

		
		//Sets color and frameNum to material instance
		matInstance->SetVectorParameterValue("Color", randColor);
		matInstance->SetScalarParameterValue("Frame", frameNum);
		
		//Checks that a color for the particle is assigned to prevent an engine crash
		if (colorParticle)
		{
			//Creates the particle component, sets its color to the randColor vector, destroys the projectile on spawn of particle and disables collision for the
			//projectile
			UNiagaraComponent* particleComp = UNiagaraFunctionLibrary::SpawnSystemAttached(colorParticle, HitComp, NAME_None, FVector(0.f), FRotator(0.f), EAttachLocation::KeepRelativeOffset, true);
			particleComp->SetNiagaraVariableLinearColor(FString("RandColor"), randColor);
			ProjectileMesh->DestroyComponent();
			CollisionComp->BodyInstance.SetCollisionProfileName("NoCollision");
			
		}
	}
}
